name: CD Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Guardar nueva versión
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin main
          git pull --rebase origin main

          git add README.md

          if ! git diff --cached --quiet; then
            git commit -m "cd: incrementar versión"
          fi

          git push origin HEAD:main

  validate-prod:
    needs: bump-version
    runs-on: self-hosted
    steps:
      - name: Validar PROD_TOKEN en Runner Self-Hosted
        run: |
          if ($env:LOCAL_PROD_TOKEN -eq "${{ secrets.PROD_TOKEN }}") {
            echo "Token PROD verificado correctamente."
            exit 0
          } else {
            echo "Error: El token PROD local no coincide con el secret."
            exit 1
          }
