name: CD Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Incrementar versión en README.md
        run: |
          git checkout -B main origin/main
          CURRENT_DATE=$(date +'%Y-%m-%d %H:%M:%S')

          if grep -q "AppVersion-" README.md; then
            LAST_VER=$(grep -o 'AppVersion-[0-9]*' README.md | tail -n 1 | cut -d'-' -f2)
            NEW_VER=$((LAST_VER + 1))
            echo "AppVersion-$NEW_VER ($CURRENT_DATE)" >> README.md
          else
            echo "AppVersion-1 ($CURRENT_DATE)" >> README.md
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: incrementar version en README.md"
          git push origin main

  validate-prod:
    needs: bump-version
    runs-on: self-hosted
    steps:
      - name: Validar PROD_TOKEN en Runner Self-Hosted
        run: |
          if [ "$LOCAL_PROD_TOKEN" = "${{ secrets.PROD_TOKEN }}" ]; then
            echo "Token PROD verificado correctamente."
            exit 0
          else
            echo "Error: El token PROD local no coincide con el secret."
            exit 1
          fi
